api/urls.py
from django.urls import path
from .views import CreateQRView, RegisterUsers, LoginView, SongsDetailView, LogoutView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('create/', CreateQRView.as_view(), name="songs-list-create"),
    path('songs/<int:pk>/', SongsDetailView.as_view(), name="songs-detail"),
    path('auth/login/', LoginView.as_view(), name="auth-login"),
    path('auth/logout/', LogoutView.as_view(), name="auth-logout"),
    path('auth/register/', RegisterUsers.as_view(), name="auth-register"),
    path('auth/token/', obtain_auth_token, name='auth-token'),

]

main/urls.py
from django.conf.urls import url
from . import views
from api.views import CreateQRView

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^generate-qr$', views.generate_qr, name='generate_qr'),

]

qr_api/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('api/', include(('api.urls', 'api'), namespace='api'))

]

api/models.py
from django.db import models


class Songs(models.Model):
    # song title
    title = models.CharField(max_length=255, null=False)
    # name of artist or group/band
    artist = models.CharField(max_length=255, null=False)

    def __str__(self):
        return "{} - {}".format(self.title, self.artist)

main/models.py
from django.db import models

# Create your models here.

api/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.db.utils import IntegrityError
from django.contrib.auth.hashers import check_password

from rest_framework import generics
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.views import status, APIView
from rest_framework.throttling import UserRateThrottle, AnonRateThrottle
from rest_framework.authtoken.models import Token

from .decorators import validate_request_data
from .serializers import *
from .utils import generate_qr
from .models import Songs


class CreateQRView(generics.CreateAPIView):
    """
    POST create/
    """
    permission_classes = (permissions.AllowAny,)
    queryset = ''
    serializer_class = QRSerializer
    throttle_classes = [AnonRateThrottle]

    @validate_request_data
    def post(self, request, *args, **kwargs):
        text = request.data['text']
        output = generate_qr(text)
        result = QRSerializer(output).data
        return Response(
            data=result,
            status=status.HTTP_201_CREATED
        )


class SongsDetailView(generics.RetrieveUpdateDestroyAPIView):
    """
    GET songs/:id/
    PUT songs/:id/
    DELETE songs/:id/
    """
    permission_classes = (permissions.IsAuthenticated,)
    queryset = Songs.objects.all()
    serializer_class = SongsSerializer
    throttle_class = [UserRateThrottle]

    def get(self, request, *args, **kwargs):
        try:
            a_song = self.queryset.get(pk=kwargs["pk"])
            return Response(SongsSerializer(a_song).data)
        except Songs.DoesNotExist:
            return Response(
                data={
                    "message": "Song with id: {} does not exist".format(kwargs["pk"])
                },
                status=status.HTTP_404_NOT_FOUND
            )

    def put(self, request, *args, **kwargs):
        try:
            a_song = self.queryset.get(pk=kwargs["pk"])
            serializer = SongsSerializer()
            updated_song = serializer.update(a_song, request.data)
            return Response(SongsSerializer(updated_song).data)
        except Songs.DoesNotExist:
            return Response(
                data={
                    "message": "Song with id: {} does not exist".format(kwargs["pk"])
                },
                status=status.HTTP_404_NOT_FOUND
            )

    def delete(self, request, *args, **kwargs):
        try:
            a_song = self.queryset.get(pk=kwargs["pk"])
            a_song.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except Songs.DoesNotExist:
            return Response(
                data={
                    "message": "Song with id: {} does not exist".format(kwargs["pk"])
                },
                status=status.HTTP_404_NOT_FOUND
            )


class LoginView(generics.CreateAPIView):
    """
    POST auth/login/
    """

    # This permission class will over ride the global permission
    # class setting
    permission_classes = (permissions.AllowAny,)
    queryset = User.objects.all()
    throttle_classes = ''
    serializer_class = LoginSerializer

    def post(self, request, *args, **kwargs):
        username = request.data.get("username", None)
        password = request.data.get("password", None)
        none_check = username or password is None
        empty_check = username or password is ''
        if (none_check or empty_check) is True:
            return Response(data={"message": "Username and password required"},
                            status=status.HTTP_401_UNAUTHORIZED)
        get_password = User.objects.get(username__exact=username).password
        password_check = check_password(password, get_password)
        if password_check is True:
            user = authenticate(username=username, password=password)
            if user is not None:
                # login saves the user’s ID in the session,
                # using Django’s session framework.
                login(request, user)
                token = Token.objects.get_or_create(user=user)
                return Response(
                    data={"token": token[0].key},
                    status=status.HTTP_200_OK
                )
        else:
            return Response(
                data={"message": "Username or password incorrect"},
                status=status.HTTP_401_UNAUTHORIZED
            )


class LogoutView(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        # simply delete the session information
        request.session.flush()
        return Response(
            data={"message": "You are logged out."},
            status=status.HTTP_200_OK)


class RegisterUsers(generics.CreateAPIView):
    """
    POST auth/register/
    """
    permission_classes = (permissions.AllowAny,)
    queryset = User.objects.all()
    serializer_class = UserSerializer
    throttle_classes = ''

    def post(self, request, *args, **kwargs):
        username = request.data.get("username", "")
        password = request.data.get("password", "")
        email = request.data.get("email", "")
        if not username and not password and not email:
            return Response(
                data={
                    "message": "username, password and email is required to register a user"
                },
                status=status.HTTP_400_BAD_REQUEST
            )
        try:
            new_user = User.objects.create_user(
                username=username, password=password, email=email
            )
        except IntegrityError:
            return Response(
                data={"message": "Username and Email should be unique"},
                status=status.HTTP_400_BAD_REQUEST
            )

        return Response(
            data={"message": "User created successfully"},
            status=status.HTTP_201_CREATED
        )

main/views.py
from django.shortcuts import render

import requests


def home(request):
    return render(request, 'main/index.html')


def generate_qr(request):
    url_text = request.POST.get('url', None)
    api_text = {"text": url_text}
    api_endpoint = "http://127.0.0.1:8000/api/create/"
    req = requests.post(url=api_endpoint,data=api_text)
    res = req.json()
    status = req.status_code
    context_dict = dict()
    if status == 429:
        context_dict['message'] = res.get('detail')
    else:
        context_dict['image_data'] = res.get('image_base64')
    return render(request, 'main/index.html', context_dict)

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form method="post" action="{% url 'main:generate_qr'%}" class="form">
                {% csrf_token %}
                <div class="form-group">
                    <textarea name="url" placeholder="Enter url" rows="10" class="form-control" required></textarea>
                </div>
                <button type="submit" name="generate" class="btn btn-primary">Generate</button>
            </form>
        </div>
        {% if message %}
        <div class="col-md-4 offset-md-4 p-3">
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
        </div>
        {% else %}
        <div class="col-md-4 offset-md-4 p-3">
            <img src="data:image/png;base64, {{image_data}}" class="img-fluid img-thumbnail rounded"><br>
            <a href="data:image/png;base64, {{image_data}}" download="filename.png">Download qr code</a>
        </div>

        {% endif %}


    </div>

</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">  
  <a class="navbar-brand" href="/">
      QR Code
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav" style="margin-top: 0px;margin-right: -31px;">

      <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item dropdown mr-auto">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Types
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                <a class="dropdown-item" href="#">URL</a>
                <a class="dropdown-item" href="#">VCard</a>
                <a class="dropdown-item" href="#">Text</a>
                <a class="dropdown-item" href="#">E-mail</a>
                <a class="dropdown-item" href="#">SMS</a>
                <a class="dropdown-item" href="#">Facebook</a>
                <a class="dropdown-item" href="#">PDF</a>
                <a class="dropdown-item" href="#">MP3</a>
                <a class="dropdown-item" href="#">App Stores</a>
                <a class="dropdown-item" href="#">Images</a>
              </div>
            </li>
      </ul>
    </ul>
  </div>
      
</nav>